'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization
Imports System.IO
Imports System.IO.File

Namespace NFe.ConsultaCadastro_V2
    'This source code was auto-generated by xsd, Version=2.0.50727.3038.
    '

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.portalfiscal.inf.br/nfe"), _
     System.Xml.Serialization.XmlRootAttribute("ConsCad", [Namespace]:="http://www.portalfiscal.inf.br/nfe", IsNullable:=False)> _
    Partial Public Class TConsCad

        Public Sub Save(ByVal sFileName As String)

            Dim oStreamWriter As StreamWriter

            Try

                oStreamWriter = CreateText(sFileName)
                Dim oXmlSerializer As New XmlSerializer(GetType(TConsCad))
                oXmlSerializer.Serialize(oStreamWriter, Me)

            Finally
                oStreamWriter.Close()
            End Try

        End Sub

        Public Shared Function Load(ByVal sFileName As String) As TConsCad

            Dim oFileStream As FileStream
            Dim oReturn As TConsCad

            Try

                oFileStream = OpenRead(sFileName)
                Dim oXmlSerializer As New XmlSerializer(GetType(TConsCad))
                oReturn = oXmlSerializer.Deserialize(oFileStream)

            Finally
                oFileStream.Close()
            End Try

            Return oReturn

        End Function


        Private infConsField As TConsCadInfCons

        Private versaoField As String

        '''<remarks/>
        Public Property infCons() As TConsCadInfCons
            Get
                Return Me.infConsField
            End Get
            Set(ByVal value As TConsCadInfCons)
                Me.infConsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")> _
        Public Property versao() As String
            Get
                Return Me.versaoField
            End Get
            Set(ByVal value As String)
                Me.versaoField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.portalfiscal.inf.br/nfe")> _
    Partial Public Class TConsCadInfCons

        Private xServField As TConsCadInfConsXServ

        Private ufField As TUfCons

        Private itemField As String

        Private itemElementNameField As ItemChoiceType

        '''<remarks/>
        Public Property xServ() As TConsCadInfConsXServ
            Get
                Return Me.xServField
            End Get
            Set(ByVal value As TConsCadInfConsXServ)
                Me.xServField = value
            End Set
        End Property

        '''<remarks/>
        Public Property UF() As TUfCons
            Get
                Return Me.ufField
            End Get
            Set(ByVal value As TUfCons)
                Me.ufField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("CNPJ", GetType(String)), _
         System.Xml.Serialization.XmlElementAttribute("CPF", GetType(String)), _
         System.Xml.Serialization.XmlElementAttribute("IE", GetType(String)), _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")> _
        Public Property Item() As String
            Get
                Return Me.itemField
            End Get
            Set(ByVal value As String)
                Me.itemField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ItemElementName() As ItemChoiceType
            Get
                Return Me.itemElementNameField
            End Get
            Set(ByVal value As ItemChoiceType)
                Me.itemElementNameField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.portalfiscal.inf.br/nfe")> _
    Public Enum TConsCadInfConsXServ

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("CONS-CAD")> _
        CONSCAD
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.portalfiscal.inf.br/nfe")> _
    Public Enum TUfCons

        '''<remarks/>
        AC

        '''<remarks/>
        AL

        '''<remarks/>
        AM

        '''<remarks/>
        AP

        '''<remarks/>
        BA

        '''<remarks/>
        CE

        '''<remarks/>
        DF

        '''<remarks/>
        ES

        '''<remarks/>
        GO

        '''<remarks/>
        MA

        '''<remarks/>
        MG

        '''<remarks/>
        MS

        '''<remarks/>
        MT

        '''<remarks/>
        PA

        '''<remarks/>
        PB

        '''<remarks/>
        PE

        '''<remarks/>
        PI

        '''<remarks/>
        PR

        '''<remarks/>
        RJ

        '''<remarks/>
        RN

        '''<remarks/>
        RO

        '''<remarks/>
        RR

        '''<remarks/>
        RS

        '''<remarks/>
        SC

        '''<remarks/>
        SE

        '''<remarks/>
        SP

        '''<remarks/>
        [TO]

        '''<remarks/>
        SU
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.portalfiscal.inf.br/nfe", IncludeInSchema:=False)> _
    Public Enum ItemChoiceType

        '''<remarks/>
        CNPJ

        '''<remarks/>
        CPF

        '''<remarks/>
        IE
    End Enum
End Namespace
