'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4927.
'
Namespace br.com.ginfes.producao
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceGinfesImplBinding", [Namespace]:="http://producao.ginfes.com.br")>  _
    Partial Public Class ServiceGinfesImplService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CancelarNfseOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CancelarNfseV3OperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarLoteRpsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarLoteRpsV3OperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarNfseOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarNfsePorRpsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarNfsePorRpsV3OperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarNfseV3OperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarSituacaoLoteRpsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarSituacaoLoteRpsV3OperationCompleted As System.Threading.SendOrPostCallback
        
        Private RecepcionarLoteRpsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RecepcionarLoteRpsV3OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "https://producao.ginfes.com.br//ServiceGinfesImpl"
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CancelarNfseCompleted As CancelarNfseCompletedEventHandler
        
        '''<remarks/>
        Public Event CancelarNfseV3Completed As CancelarNfseV3CompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarLoteRpsCompleted As ConsultarLoteRpsCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarLoteRpsV3Completed As ConsultarLoteRpsV3CompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarNfseCompleted As ConsultarNfseCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarNfsePorRpsCompleted As ConsultarNfsePorRpsCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarNfsePorRpsV3Completed As ConsultarNfsePorRpsV3CompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarNfseV3Completed As ConsultarNfseV3CompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarSituacaoLoteRpsCompleted As ConsultarSituacaoLoteRpsCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarSituacaoLoteRpsV3Completed As ConsultarSituacaoLoteRpsV3CompletedEventHandler
        
        '''<remarks/>
        Public Event RecepcionarLoteRpsCompleted As RecepcionarLoteRpsCompletedEventHandler
        
        '''<remarks/>
        Public Event RecepcionarLoteRpsV3Completed As RecepcionarLoteRpsV3CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://producao.ginfes.com.br", ResponseNamespace:="http://producao.ginfes.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function CancelarNfse(ByVal arg0 As String) As <System.Xml.Serialization.XmlElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("CancelarNfse", New Object() {arg0})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CancelarNfseAsync(ByVal arg0 As String)
            Me.CancelarNfseAsync(arg0, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CancelarNfseAsync(ByVal arg0 As String, ByVal userState As Object)
            If (Me.CancelarNfseOperationCompleted Is Nothing) Then
                Me.CancelarNfseOperationCompleted = AddressOf Me.OnCancelarNfseOperationCompleted
            End If
            Me.InvokeAsync("CancelarNfse", New Object() {arg0}, Me.CancelarNfseOperationCompleted, userState)
        End Sub
        
        Private Sub OnCancelarNfseOperationCompleted(ByVal arg As Object)
            If (Not (Me.CancelarNfseCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CancelarNfseCompleted(Me, New CancelarNfseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://producao.ginfes.com.br", ResponseNamespace:="http://producao.ginfes.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function CancelarNfseV3(ByVal arg0 As String, ByVal arg1 As String) As <System.Xml.Serialization.XmlElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("CancelarNfseV3", New Object() {arg0, arg1})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CancelarNfseV3Async(ByVal arg0 As String, ByVal arg1 As String)
            Me.CancelarNfseV3Async(arg0, arg1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CancelarNfseV3Async(ByVal arg0 As String, ByVal arg1 As String, ByVal userState As Object)
            If (Me.CancelarNfseV3OperationCompleted Is Nothing) Then
                Me.CancelarNfseV3OperationCompleted = AddressOf Me.OnCancelarNfseV3OperationCompleted
            End If
            Me.InvokeAsync("CancelarNfseV3", New Object() {arg0, arg1}, Me.CancelarNfseV3OperationCompleted, userState)
        End Sub
        
        Private Sub OnCancelarNfseV3OperationCompleted(ByVal arg As Object)
            If (Not (Me.CancelarNfseV3CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CancelarNfseV3Completed(Me, New CancelarNfseV3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://producao.ginfes.com.br", ResponseNamespace:="http://producao.ginfes.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function ConsultarLoteRps(ByVal arg0 As String) As <System.Xml.Serialization.XmlElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("ConsultarLoteRps", New Object() {arg0})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarLoteRpsAsync(ByVal arg0 As String)
            Me.ConsultarLoteRpsAsync(arg0, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarLoteRpsAsync(ByVal arg0 As String, ByVal userState As Object)
            If (Me.ConsultarLoteRpsOperationCompleted Is Nothing) Then
                Me.ConsultarLoteRpsOperationCompleted = AddressOf Me.OnConsultarLoteRpsOperationCompleted
            End If
            Me.InvokeAsync("ConsultarLoteRps", New Object() {arg0}, Me.ConsultarLoteRpsOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarLoteRpsOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarLoteRpsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarLoteRpsCompleted(Me, New ConsultarLoteRpsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://producao.ginfes.com.br", ResponseNamespace:="http://producao.ginfes.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function ConsultarLoteRpsV3(ByVal arg0 As String, ByVal arg1 As String) As <System.Xml.Serialization.XmlElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("ConsultarLoteRpsV3", New Object() {arg0, arg1})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarLoteRpsV3Async(ByVal arg0 As String, ByVal arg1 As String)
            Me.ConsultarLoteRpsV3Async(arg0, arg1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarLoteRpsV3Async(ByVal arg0 As String, ByVal arg1 As String, ByVal userState As Object)
            If (Me.ConsultarLoteRpsV3OperationCompleted Is Nothing) Then
                Me.ConsultarLoteRpsV3OperationCompleted = AddressOf Me.OnConsultarLoteRpsV3OperationCompleted
            End If
            Me.InvokeAsync("ConsultarLoteRpsV3", New Object() {arg0, arg1}, Me.ConsultarLoteRpsV3OperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarLoteRpsV3OperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarLoteRpsV3CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarLoteRpsV3Completed(Me, New ConsultarLoteRpsV3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://producao.ginfes.com.br", ResponseNamespace:="http://producao.ginfes.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function ConsultarNfse(ByVal arg0 As String) As <System.Xml.Serialization.XmlElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("ConsultarNfse", New Object() {arg0})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarNfseAsync(ByVal arg0 As String)
            Me.ConsultarNfseAsync(arg0, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarNfseAsync(ByVal arg0 As String, ByVal userState As Object)
            If (Me.ConsultarNfseOperationCompleted Is Nothing) Then
                Me.ConsultarNfseOperationCompleted = AddressOf Me.OnConsultarNfseOperationCompleted
            End If
            Me.InvokeAsync("ConsultarNfse", New Object() {arg0}, Me.ConsultarNfseOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarNfseOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarNfseCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarNfseCompleted(Me, New ConsultarNfseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://producao.ginfes.com.br", ResponseNamespace:="http://producao.ginfes.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function ConsultarNfsePorRps(ByVal arg0 As String) As <System.Xml.Serialization.XmlElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("ConsultarNfsePorRps", New Object() {arg0})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarNfsePorRpsAsync(ByVal arg0 As String)
            Me.ConsultarNfsePorRpsAsync(arg0, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarNfsePorRpsAsync(ByVal arg0 As String, ByVal userState As Object)
            If (Me.ConsultarNfsePorRpsOperationCompleted Is Nothing) Then
                Me.ConsultarNfsePorRpsOperationCompleted = AddressOf Me.OnConsultarNfsePorRpsOperationCompleted
            End If
            Me.InvokeAsync("ConsultarNfsePorRps", New Object() {arg0}, Me.ConsultarNfsePorRpsOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarNfsePorRpsOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarNfsePorRpsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarNfsePorRpsCompleted(Me, New ConsultarNfsePorRpsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://producao.ginfes.com.br", ResponseNamespace:="http://producao.ginfes.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function ConsultarNfsePorRpsV3(ByVal arg0 As String, ByVal arg1 As String) As <System.Xml.Serialization.XmlElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("ConsultarNfsePorRpsV3", New Object() {arg0, arg1})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarNfsePorRpsV3Async(ByVal arg0 As String, ByVal arg1 As String)
            Me.ConsultarNfsePorRpsV3Async(arg0, arg1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarNfsePorRpsV3Async(ByVal arg0 As String, ByVal arg1 As String, ByVal userState As Object)
            If (Me.ConsultarNfsePorRpsV3OperationCompleted Is Nothing) Then
                Me.ConsultarNfsePorRpsV3OperationCompleted = AddressOf Me.OnConsultarNfsePorRpsV3OperationCompleted
            End If
            Me.InvokeAsync("ConsultarNfsePorRpsV3", New Object() {arg0, arg1}, Me.ConsultarNfsePorRpsV3OperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarNfsePorRpsV3OperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarNfsePorRpsV3CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarNfsePorRpsV3Completed(Me, New ConsultarNfsePorRpsV3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://producao.ginfes.com.br", ResponseNamespace:="http://producao.ginfes.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function ConsultarNfseV3(ByVal arg0 As String, ByVal arg1 As String) As <System.Xml.Serialization.XmlElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("ConsultarNfseV3", New Object() {arg0, arg1})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarNfseV3Async(ByVal arg0 As String, ByVal arg1 As String)
            Me.ConsultarNfseV3Async(arg0, arg1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarNfseV3Async(ByVal arg0 As String, ByVal arg1 As String, ByVal userState As Object)
            If (Me.ConsultarNfseV3OperationCompleted Is Nothing) Then
                Me.ConsultarNfseV3OperationCompleted = AddressOf Me.OnConsultarNfseV3OperationCompleted
            End If
            Me.InvokeAsync("ConsultarNfseV3", New Object() {arg0, arg1}, Me.ConsultarNfseV3OperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarNfseV3OperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarNfseV3CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarNfseV3Completed(Me, New ConsultarNfseV3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://producao.ginfes.com.br", ResponseNamespace:="http://producao.ginfes.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function ConsultarSituacaoLoteRps(ByVal arg0 As String) As <System.Xml.Serialization.XmlElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("ConsultarSituacaoLoteRps", New Object() {arg0})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarSituacaoLoteRpsAsync(ByVal arg0 As String)
            Me.ConsultarSituacaoLoteRpsAsync(arg0, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarSituacaoLoteRpsAsync(ByVal arg0 As String, ByVal userState As Object)
            If (Me.ConsultarSituacaoLoteRpsOperationCompleted Is Nothing) Then
                Me.ConsultarSituacaoLoteRpsOperationCompleted = AddressOf Me.OnConsultarSituacaoLoteRpsOperationCompleted
            End If
            Me.InvokeAsync("ConsultarSituacaoLoteRps", New Object() {arg0}, Me.ConsultarSituacaoLoteRpsOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarSituacaoLoteRpsOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarSituacaoLoteRpsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarSituacaoLoteRpsCompleted(Me, New ConsultarSituacaoLoteRpsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://producao.ginfes.com.br", ResponseNamespace:="http://producao.ginfes.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function ConsultarSituacaoLoteRpsV3(ByVal arg0 As String, ByVal arg1 As String) As <System.Xml.Serialization.XmlElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("ConsultarSituacaoLoteRpsV3", New Object() {arg0, arg1})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarSituacaoLoteRpsV3Async(ByVal arg0 As String, ByVal arg1 As String)
            Me.ConsultarSituacaoLoteRpsV3Async(arg0, arg1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarSituacaoLoteRpsV3Async(ByVal arg0 As String, ByVal arg1 As String, ByVal userState As Object)
            If (Me.ConsultarSituacaoLoteRpsV3OperationCompleted Is Nothing) Then
                Me.ConsultarSituacaoLoteRpsV3OperationCompleted = AddressOf Me.OnConsultarSituacaoLoteRpsV3OperationCompleted
            End If
            Me.InvokeAsync("ConsultarSituacaoLoteRpsV3", New Object() {arg0, arg1}, Me.ConsultarSituacaoLoteRpsV3OperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarSituacaoLoteRpsV3OperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarSituacaoLoteRpsV3CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarSituacaoLoteRpsV3Completed(Me, New ConsultarSituacaoLoteRpsV3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://producao.ginfes.com.br", ResponseNamespace:="http://producao.ginfes.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function RecepcionarLoteRps(ByVal arg0 As String) As <System.Xml.Serialization.XmlElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("RecepcionarLoteRps", New Object() {arg0})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RecepcionarLoteRpsAsync(ByVal arg0 As String)
            Me.RecepcionarLoteRpsAsync(arg0, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RecepcionarLoteRpsAsync(ByVal arg0 As String, ByVal userState As Object)
            If (Me.RecepcionarLoteRpsOperationCompleted Is Nothing) Then
                Me.RecepcionarLoteRpsOperationCompleted = AddressOf Me.OnRecepcionarLoteRpsOperationCompleted
            End If
            Me.InvokeAsync("RecepcionarLoteRps", New Object() {arg0}, Me.RecepcionarLoteRpsOperationCompleted, userState)
        End Sub
        
        Private Sub OnRecepcionarLoteRpsOperationCompleted(ByVal arg As Object)
            If (Not (Me.RecepcionarLoteRpsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RecepcionarLoteRpsCompleted(Me, New RecepcionarLoteRpsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://producao.ginfes.com.br", ResponseNamespace:="http://producao.ginfes.com.br", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function RecepcionarLoteRpsV3(ByVal arg0 As String, ByVal arg1 As String) As <System.Xml.Serialization.XmlElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("RecepcionarLoteRpsV3", New Object() {arg0, arg1})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RecepcionarLoteRpsV3Async(ByVal arg0 As String, ByVal arg1 As String)
            Me.RecepcionarLoteRpsV3Async(arg0, arg1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RecepcionarLoteRpsV3Async(ByVal arg0 As String, ByVal arg1 As String, ByVal userState As Object)
            If (Me.RecepcionarLoteRpsV3OperationCompleted Is Nothing) Then
                Me.RecepcionarLoteRpsV3OperationCompleted = AddressOf Me.OnRecepcionarLoteRpsV3OperationCompleted
            End If
            Me.InvokeAsync("RecepcionarLoteRpsV3", New Object() {arg0, arg1}, Me.RecepcionarLoteRpsV3OperationCompleted, userState)
        End Sub
        
        Private Sub OnRecepcionarLoteRpsV3OperationCompleted(ByVal arg As Object)
            If (Not (Me.RecepcionarLoteRpsV3CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RecepcionarLoteRpsV3Completed(Me, New RecepcionarLoteRpsV3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub CancelarNfseCompletedEventHandler(ByVal sender As Object, ByVal e As CancelarNfseCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CancelarNfseCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub CancelarNfseV3CompletedEventHandler(ByVal sender As Object, ByVal e As CancelarNfseV3CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CancelarNfseV3CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub ConsultarLoteRpsCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarLoteRpsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarLoteRpsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub ConsultarLoteRpsV3CompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarLoteRpsV3CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarLoteRpsV3CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub ConsultarNfseCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarNfseCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarNfseCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub ConsultarNfsePorRpsCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarNfsePorRpsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarNfsePorRpsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub ConsultarNfsePorRpsV3CompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarNfsePorRpsV3CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarNfsePorRpsV3CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub ConsultarNfseV3CompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarNfseV3CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarNfseV3CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub ConsultarSituacaoLoteRpsCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarSituacaoLoteRpsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarSituacaoLoteRpsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub ConsultarSituacaoLoteRpsV3CompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarSituacaoLoteRpsV3CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarSituacaoLoteRpsV3CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub RecepcionarLoteRpsCompletedEventHandler(ByVal sender As Object, ByVal e As RecepcionarLoteRpsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RecepcionarLoteRpsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub RecepcionarLoteRpsV3CompletedEventHandler(ByVal sender As Object, ByVal e As RecepcionarLoteRpsV3CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RecepcionarLoteRpsV3CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
