'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization
Imports System.IO.File
Imports System.IO

'
'This source code was auto-generated by xsd, Version=2.0.50727.1432.
'
Namespace NFSE.ConsultaNFSe
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd", IsNullable:=false)>  _
    Partial Public Class ListaMensagemRetorno
        
        Private mensagemRetornoField() As tcMensagemRetorno
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("MensagemRetorno")>  _
        Public Property MensagemRetorno() As tcMensagemRetorno()
            Get
                Return Me.mensagemRetornoField
            End Get
            Set
                Me.mensagemRetornoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")>  _
    Partial Public Class tcMensagemRetorno
        
        Private codigoField As String
        
        Private mensagemField As String
        
        Private correcaoField As String
        
        '''<remarks/>
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mensagem() As String
            Get
                Return Me.mensagemField
            End Get
            Set
                Me.mensagemField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Correcao() As String
            Get
                Return Me.correcaoField
            End Get
            Set
                Me.correcaoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http:/www.abrasf.org.br/nfse.xsd"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http:/www.abrasf.org.br/nfse.xsd", IsNullable:=False)> _
    Partial Public Class cabecalho
        Public Sub Save(ByVal sFileName As String)

            Dim oStreamWriter As StreamWriter

            Try

                oStreamWriter = CreateText(sFileName)
                Dim oXmlSerializer As New XmlSerializer(GetType(cabecalho))
                oXmlSerializer.Serialize(oStreamWriter, Me)

            Finally
                oStreamWriter.Close()
            End Try

        End Sub
        Private versaoDadosField As String

        Private versaoField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token")> _
        Public Property versaoDados() As String
            Get
                Return Me.versaoDadosField
            End Get
            Set(value As String)
                Me.versaoDadosField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")> _
        Public Property versao() As String
            Get
                Return Me.versaoField
            End Get
            Set(value As String)
                Me.versaoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.ginfes.com.br/servico_consultar_nfse_envio_v03.xsd"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.ginfes.com.br/servico_consultar_nfse_envio_v03.xsd", IsNullable:=false)>  _
    Partial Public Class ConsultarNfseEnvio
        Public Sub Save(ByVal sFileName As String)

            Dim oStreamWriter As StreamWriter

            Try

                oStreamWriter = CreateText(sFileName)
                Dim oXmlSerializer As New XmlSerializer(GetType(ConsultarNfseEnvio))
                oXmlSerializer.Serialize(oStreamWriter, Me)

            Finally
                oStreamWriter.Close()
            End Try

        End Sub
        Private prestadorField As tcIdentificacaoPrestador
        
        Private numeroNfseField As String
        
        Private periodoEmissaoField As ConsultarNfseEnvioPeriodoEmissao
        
        Private tomadorField As tcIdentificacaoTomador
        
        Private intermediarioServicoField As tcIdentificacaoIntermediarioServico
        
        Private signatureField As SignatureType
        
        '''<remarks/>
        Public Property Prestador() As tcIdentificacaoPrestador
            Get
                Return Me.prestadorField
            End Get
            Set
                Me.prestadorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")>  _
        Public Property NumeroNfse() As String
            Get
                Return Me.numeroNfseField
            End Get
            Set
                Me.numeroNfseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PeriodoEmissao() As ConsultarNfseEnvioPeriodoEmissao
            Get
                Return Me.periodoEmissaoField
            End Get
            Set
                Me.periodoEmissaoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tomador() As tcIdentificacaoTomador
            Get
                Return Me.tomadorField
            End Get
            Set
                Me.tomadorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IntermediarioServico() As tcIdentificacaoIntermediarioServico
            Get
                Return Me.intermediarioServicoField
            End Get
            Set
                Me.intermediarioServicoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
        Public Property Signature() As SignatureType
            Get
                Return Me.signatureField
            End Get
            Set
                Me.signatureField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")>  _
    Partial Public Class tcIdentificacaoPrestador
        
        Private cnpjField As String
        
        Private inscricaoMunicipalField As String
        
        '''<remarks/>
        Public Property Cnpj() As String
            Get
                Return Me.cnpjField
            End Get
            Set
                Me.cnpjField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InscricaoMunicipal() As String
            Get
                Return Me.inscricaoMunicipalField
            End Get
            Set
                Me.inscricaoMunicipalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.ginfes.com.br/servico_consultar_nfse_envio_v03.xsd")>  _
    Partial Public Class ConsultarNfseEnvioPeriodoEmissao
        
        Private dataInicialField As Date
        
        Private dataFinalField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property DataInicial() As Date
            Get
                Return Me.dataInicialField
            End Get
            Set
                Me.dataInicialField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property DataFinal() As Date
            Get
                Return Me.dataFinalField
            End Get
            Set
                Me.dataFinalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")>  _
    Partial Public Class tcIdentificacaoTomador
        
        Private cpfCnpjField As tcCpfCnpj
        
        Private inscricaoMunicipalField As String
        
        '''<remarks/>
        Public Property CpfCnpj() As tcCpfCnpj
            Get
                Return Me.cpfCnpjField
            End Get
            Set
                Me.cpfCnpjField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InscricaoMunicipal() As String
            Get
                Return Me.inscricaoMunicipalField
            End Get
            Set
                Me.inscricaoMunicipalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")>  _
    Partial Public Class tcCpfCnpj
        
        Private itemField As String
        
        Private itemElementNameField As ItemChoiceType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Cnpj", GetType(String)),  _
         System.Xml.Serialization.XmlElementAttribute("Cpf", GetType(String)),  _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")>  _
        Public Property Item() As String
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ItemElementName() As ItemChoiceType
            Get
                Return Me.itemElementNameField
            End Get
            Set
                Me.itemElementNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd", IncludeInSchema:=false)>  _
    Public Enum ItemChoiceType
        
        '''<remarks/>
        Cnpj
        
        '''<remarks/>
        Cpf
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")>  _
    Partial Public Class tcIdentificacaoIntermediarioServico
        
        Private razaoSocialField As String
        
        Private cpfCnpjField As tcCpfCnpj
        
        Private inscricaoMunicipalField As String
        
        '''<remarks/>
        Public Property RazaoSocial() As String
            Get
                Return Me.razaoSocialField
            End Get
            Set
                Me.razaoSocialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CpfCnpj() As tcCpfCnpj
            Get
                Return Me.cpfCnpjField
            End Get
            Set
                Me.cpfCnpjField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InscricaoMunicipal() As String
            Get
                Return Me.inscricaoMunicipalField
            End Get
            Set
                Me.inscricaoMunicipalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),  _
     System.Xml.Serialization.XmlRootAttribute("Signature", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=false)>  _
    Partial Public Class SignatureType
        
        Private signedInfoField As SignedInfoType
        
        Private signatureValueField As SignatureValueType
        
        Private keyInfoField As KeyInfoType
        
        Private objectField() As ObjectType
        
        Private idField As String
        
        '''<remarks/>
        Public Property SignedInfo() As SignedInfoType
            Get
                Return Me.signedInfoField
            End Get
            Set
                Me.signedInfoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SignatureValue() As SignatureValueType
            Get
                Return Me.signatureValueField
            End Get
            Set
                Me.signatureValueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property KeyInfo() As KeyInfoType
            Get
                Return Me.keyInfoField
            End Get
            Set
                Me.keyInfoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Object")>  _
        Public Property [Object]() As ObjectType()
            Get
                Return Me.objectField
            End Get
            Set
                Me.objectField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),  _
     System.Xml.Serialization.XmlRootAttribute("SignedInfo", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=false)>  _
    Partial Public Class SignedInfoType
        
        Private canonicalizationMethodField As CanonicalizationMethodType
        
        Private signatureMethodField As SignatureMethodType
        
        Private referenceField() As ReferenceType
        
        Private idField As String
        
        '''<remarks/>
        Public Property CanonicalizationMethod() As CanonicalizationMethodType
            Get
                Return Me.canonicalizationMethodField
            End Get
            Set
                Me.canonicalizationMethodField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SignatureMethod() As SignatureMethodType
            Get
                Return Me.signatureMethodField
            End Get
            Set
                Me.signatureMethodField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Reference")>  _
        Public Property Reference() As ReferenceType()
            Get
                Return Me.referenceField
            End Get
            Set
                Me.referenceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),  _
     System.Xml.Serialization.XmlRootAttribute("CanonicalizationMethod", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=false)>  _
    Partial Public Class CanonicalizationMethodType
        
        Private anyField() As System.Xml.XmlNode
        
        Private algorithmField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),  _
     System.Xml.Serialization.XmlRootAttribute("SignatureMethod", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=false)>  _
    Partial Public Class SignatureMethodType
        
        Private hMACOutputLengthField As String
        
        Private anyField() As System.Xml.XmlNode
        
        Private algorithmField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property HMACOutputLength() As String
            Get
                Return Me.hMACOutputLengthField
            End Get
            Set
                Me.hMACOutputLengthField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),  _
     System.Xml.Serialization.XmlRootAttribute("Reference", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=false)>  _
    Partial Public Class ReferenceType
        
        Private transformsField() As TransformType
        
        Private digestMethodField As DigestMethodType
        
        Private digestValueField() As Byte
        
        Private idField As String
        
        Private uRIField As String
        
        Private typeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable:=false)>  _
        Public Property Transforms() As TransformType()
            Get
                Return Me.transformsField
            End Get
            Set
                Me.transformsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DigestMethod() As DigestMethodType
            Get
                Return Me.digestMethodField
            End Get
            Set
                Me.digestMethodField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property DigestValue() As Byte()
            Get
                Return Me.digestValueField
            End Get
            Set
                Me.digestValueField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property URI() As String
            Get
                Return Me.uRIField
            End Get
            Set
                Me.uRIField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"),  _
     System.Xml.Serialization.XmlRootAttribute("Transform", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=false)>  _
    Partial Public Class TransformType
        
        Private itemsField() As Object
        
        Private textField() As String
        
        Private algorithmField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(),  _
         System.Xml.Serialization.XmlElementAttribute("XPath", GetType(String))>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.TextField
            End Get
            Set(value As String())
                Me.TextField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set(value As String)
                Me.algorithmField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("DigestMethod", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class DigestMethodType

        Private anyField() As System.Xml.XmlNode

        Private algorithmField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(), _
         System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set(value As System.Xml.XmlNode())
                Me.anyField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set(value As String)
                Me.algorithmField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("SignatureValue", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class SignatureValueType

        Private idField As String

        Private valueField() As Byte

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(value As String)
                Me.idField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="base64Binary")> _
        Public Property Value() As Byte()
            Get
                Return Me.valueField
            End Get
            Set(value As Byte())
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("KeyInfo", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class KeyInfoType

        Private itemsField() As Object

        Private itemsElementNameField() As ItemsChoiceType2

        Private textField() As String

        Private idField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(), _
         System.Xml.Serialization.XmlElementAttribute("KeyName", GetType(String)), _
         System.Xml.Serialization.XmlElementAttribute("KeyValue", GetType(KeyValueType)), _
         System.Xml.Serialization.XmlElementAttribute("MgmtData", GetType(String)), _
         System.Xml.Serialization.XmlElementAttribute("PGPData", GetType(PGPDataType)), _
         System.Xml.Serialization.XmlElementAttribute("RetrievalMethod", GetType(RetrievalMethodType)), _
         System.Xml.Serialization.XmlElementAttribute("SPKIData", GetType(SPKIDataType)), _
         System.Xml.Serialization.XmlElementAttribute("X509Data", GetType(X509DataType)), _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")> _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set(value As Object())
                Me.itemsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"), _
         System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ItemsElementName() As ItemsChoiceType2()
            Get
                Return Me.itemsElementNameField
            End Get
            Set(value As ItemsChoiceType2())
                Me.itemsElementNameField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.TextField
            End Get
            Set(value As String())
                Me.TextField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(value As String)
                Me.idField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("KeyValue", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class KeyValueType

        Private itemField As Object

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(), _
         System.Xml.Serialization.XmlElementAttribute("DSAKeyValue", GetType(DSAKeyValueType)), _
         System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", GetType(RSAKeyValueType))> _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set(value As Object)
                Me.itemField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.TextField
            End Get
            Set(value As String())
                Me.TextField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("DSAKeyValue", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class DSAKeyValueType

        Private pField() As Byte

        Private qField() As Byte

        Private gField() As Byte

        Private yField() As Byte

        Private jField() As Byte

        Private seedField() As Byte

        Private pgenCounterField() As Byte

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property P() As Byte()
            Get
                Return Me.pField
            End Get
            Set(value As Byte())
                Me.pField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property Q() As Byte()
            Get
                Return Me.qField
            End Get
            Set(value As Byte())
                Me.qField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property G() As Byte()
            Get
                Return Me.gField
            End Get
            Set(value As Byte())
                Me.gField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property Y() As Byte()
            Get
                Return Me.yField
            End Get
            Set(value As Byte())
                Me.yField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property J() As Byte()
            Get
                Return Me.jField
            End Get
            Set(value As Byte())
                Me.jField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property Seed() As Byte()
            Get
                Return Me.seedField
            End Get
            Set(value As Byte())
                Me.seedField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property PgenCounter() As Byte()
            Get
                Return Me.pgenCounterField
            End Get
            Set(value As Byte())
                Me.pgenCounterField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("RSAKeyValue", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class RSAKeyValueType

        Private modulusField() As Byte

        Private exponentField() As Byte

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property Modulus() As Byte()
            Get
                Return Me.modulusField
            End Get
            Set(value As Byte())
                Me.modulusField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property Exponent() As Byte()
            Get
                Return Me.exponentField
            End Get
            Set(value As Byte())
                Me.exponentField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("PGPData", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class PGPDataType

        Private itemsField() As Object

        Private itemsElementNameField() As ItemsChoiceType1

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(), _
         System.Xml.Serialization.XmlElementAttribute("PGPKeyID", GetType(Byte()), DataType:="base64Binary"), _
         System.Xml.Serialization.XmlElementAttribute("PGPKeyPacket", GetType(Byte()), DataType:="base64Binary"), _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")> _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set(value As Object())
                Me.itemsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"), _
         System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ItemsElementName() As ItemsChoiceType1()
            Get
                Return Me.itemsElementNameField
            End Get
            Set(value As ItemsChoiceType1())
                Me.itemsElementNameField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema:=False)> _
    Public Enum ItemsChoiceType1

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("##any:")> _
        Item

        '''<remarks/>
        PGPKeyID

        '''<remarks/>
        PGPKeyPacket
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("RetrievalMethod", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class RetrievalMethodType

        Private transformsField() As TransformType

        Private uRIField As String

        Private typeField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable:=False)> _
        Public Property Transforms() As TransformType()
            Get
                Return Me.transformsField
            End Get
            Set(value As TransformType())
                Me.transformsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property URI() As String
            Get
                Return Me.uRIField
            End Get
            Set(value As String)
                Me.uRIField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set(value As String)
                Me.typeField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("SPKIData", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class SPKIDataType

        Private sPKISexpField()() As Byte

        Private anyField As System.Xml.XmlElement

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("SPKISexp", DataType:="base64Binary")> _
        Public Property SPKISexp() As Byte()()
            Get
                Return Me.sPKISexpField
            End Get
            Set(value As Byte()())
                Me.sPKISexpField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlElement
            Get
                Return Me.anyField
            End Get
            Set(value As System.Xml.XmlElement)
                Me.anyField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("X509Data", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class X509DataType

        Private itemsField() As Object

        Private itemsElementNameField() As ItemsChoiceType

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(), _
         System.Xml.Serialization.XmlElementAttribute("X509CRL", GetType(Byte()), DataType:="base64Binary"), _
         System.Xml.Serialization.XmlElementAttribute("X509Certificate", GetType(Byte()), DataType:="base64Binary"), _
         System.Xml.Serialization.XmlElementAttribute("X509IssuerSerial", GetType(X509IssuerSerialType)), _
         System.Xml.Serialization.XmlElementAttribute("X509SKI", GetType(Byte()), DataType:="base64Binary"), _
         System.Xml.Serialization.XmlElementAttribute("X509SubjectName", GetType(String)), _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")> _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set(value As Object())
                Me.itemsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"), _
         System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ItemsElementName() As ItemsChoiceType()
            Get
                Return Me.itemsElementNameField
            End Get
            Set(value As ItemsChoiceType())
                Me.itemsElementNameField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")> _
    Partial Public Class X509IssuerSerialType

        Private x509IssuerNameField As String

        Private x509SerialNumberField As String

        '''<remarks/>
        Public Property X509IssuerName() As String
            Get
                Return Me.x509IssuerNameField
            End Get
            Set(value As String)
                Me.x509IssuerNameField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")> _
        Public Property X509SerialNumber() As String
            Get
                Return Me.x509SerialNumberField
            End Get
            Set(value As String)
                Me.x509SerialNumberField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema:=False)> _
    Public Enum ItemsChoiceType

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("##any:")> _
        Item

        '''<remarks/>
        X509CRL

        '''<remarks/>
        X509Certificate

        '''<remarks/>
        X509IssuerSerial

        '''<remarks/>
        X509SKI

        '''<remarks/>
        X509SubjectName
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema:=False)> _
    Public Enum ItemsChoiceType2

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("##any:")> _
        Item

        '''<remarks/>
        KeyName

        '''<remarks/>
        KeyValue

        '''<remarks/>
        MgmtData

        '''<remarks/>
        PGPData

        '''<remarks/>
        RetrievalMethod

        '''<remarks/>
        SPKIData

        '''<remarks/>
        X509Data
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("Object", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class ObjectType

        Private anyField() As System.Xml.XmlNode

        Private idField As String

        Private mimeTypeField As String

        Private encodingField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(), _
         System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set(value As System.Xml.XmlNode())
                Me.anyField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(value As String)
                Me.idField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property MimeType() As String
            Get
                Return Me.mimeTypeField
            End Get
            Set(value As String)
                Me.mimeTypeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property Encoding() As String
            Get
                Return Me.encodingField
            End Get
            Set(value As String)
                Me.encodingField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("Transforms", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class TransformsType

        Private transformField() As TransformType

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Transform")> _
        Public Property Transform() As TransformType()
            Get
                Return Me.transformField
            End Get
            Set(value As TransformType())
                Me.transformField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("Manifest", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class ManifestType

        Private referenceField() As ReferenceType

        Private idField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Reference")> _
        Public Property Reference() As ReferenceType()
            Get
                Return Me.referenceField
            End Get
            Set(value As ReferenceType())
                Me.referenceField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(value As String)
                Me.idField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("SignatureProperties", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class SignaturePropertiesType

        Private signaturePropertyField() As SignaturePropertyType

        Private idField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("SignatureProperty")> _
        Public Property SignatureProperty() As SignaturePropertyType()
            Get
                Return Me.signaturePropertyField
            End Get
            Set(value As SignaturePropertyType())
                Me.signaturePropertyField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(value As String)
                Me.idField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("SignatureProperty", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class SignaturePropertyType

        Private itemsField() As System.Xml.XmlElement

        Private textField() As String

        Private targetField As String

        Private idField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Items() As System.Xml.XmlElement()
            Get
                Return Me.itemsField
            End Get
            Set(value As System.Xml.XmlElement())
                Me.itemsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.TextField
            End Get
            Set(value As String())
                Me.TextField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property Target() As String
            Get
                Return Me.targetField
            End Get
            Set(value As String)
                Me.targetField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(value As String)
                Me.idField = Value
            End Set
        End Property
    End Class
End Namespace
