'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization
Imports System.IO.File
Imports System.IO

'
'This source code was auto-generated by xsd, Version=2.0.50727.1432.
'
Namespace NFSE.EnvioLoteRPS

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd", IsNullable:=False)> _
    Partial Public Class ListaMensagemRetorno

        Private mensagemRetornoField() As tcMensagemRetorno

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("MensagemRetorno")> _
        Public Property MensagemRetorno() As tcMensagemRetorno()
            Get
                Return Me.mensagemRetornoField
            End Get
            Set(ByVal value As tcMensagemRetorno())
                Me.mensagemRetornoField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")> _
    Partial Public Class tcMensagemRetorno

        Private codigoField As String

        Private mensagemField As String

        Private correcaoField As String

        '''<remarks/>
        Public Property Codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set(ByVal value As String)
                Me.codigoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Mensagem() As String
            Get
                Return Me.mensagemField
            End Get
            Set(ByVal value As String)
                Me.mensagemField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Correcao() As String
            Get
                Return Me.correcaoField
            End Get
            Set(ByVal value As String)
                Me.correcaoField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.ginfes.com.br/cabecalho_v03.xsd"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.ginfes.com.br/cabecalho_v03.xsd", IsNullable:=False)> _
    Partial Public Class cabecalho
        Public Sub Save(ByVal sFileName As String)

            Dim oStreamWriter As StreamWriter

            Try

                oStreamWriter = CreateText(sFileName)
                Dim oXmlSerializer As New XmlSerializer(GetType(cabecalho))
                oXmlSerializer.Serialize(oStreamWriter, Me)

            Finally
                oStreamWriter.Close()
            End Try

        End Sub
        Private versaoDadosField As String

        Private versaoField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="token")> _
        Public Property versaoDados() As String
            Get
                Return Me.versaoDadosField
            End Get
            Set(ByVal value As String)
                Me.versaoDadosField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")> _
        Public Property versao() As String
            Get
                Return Me.versaoField
            End Get
            Set(ByVal value As String)
                Me.versaoField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.ginfes.com.br/servico_enviar_lote_rps_envio_v03.xsd"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.ginfes.com.br/servico_enviar_lote_rps_envio_v03.xsd", IsNullable:=False)> _
    Partial Public Class EnviarLoteRpsEnvio
        Public Sub Save(ByVal sFileName As String)

            Dim oStreamWriter As StreamWriter

            Try

                oStreamWriter = CreateText(sFileName)
                Dim oXmlSerializer As New XmlSerializer(GetType(EnviarLoteRpsEnvio))
                oXmlSerializer.Serialize(oStreamWriter, Me)

            Finally
                oStreamWriter.Close()
            End Try

        End Sub
        Private loteRpsField As tcLoteRps

        Private signatureField As SignatureType

        '''<remarks/>
        Public Property LoteRps() As tcLoteRps
            Get
                Return Me.loteRpsField
            End Get
            Set(ByVal value As tcLoteRps)
                Me.loteRpsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")> _
        Public Property Signature() As SignatureType
            Get
                Return Me.signatureField
            End Get
            Set(ByVal value As SignatureType)
                Me.signatureField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")> _
    Partial Public Class tcLoteRps

        Private numeroLoteField As String

        Private cnpjField As String

        Private inscricaoMunicipalField As String

        Private quantidadeRpsField As Integer

        Private listaRpsField() As tcRps

        Private idField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")> _
        Public Property NumeroLote() As String
            Get
                Return Me.numeroLoteField
            End Get
            Set(ByVal value As String)
                Me.numeroLoteField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Cnpj() As String
            Get
                Return Me.cnpjField
            End Get
            Set(ByVal value As String)
                Me.cnpjField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property InscricaoMunicipal() As String
            Get
                Return Me.inscricaoMunicipalField
            End Get
            Set(ByVal value As String)
                Me.inscricaoMunicipalField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property QuantidadeRps() As Integer
            Get
                Return Me.quantidadeRpsField
            End Get
            Set(ByVal value As Integer)
                Me.quantidadeRpsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Rps", IsNullable:=False)> _
        Public Property ListaRps() As tcRps()
            Get
                Return Me.listaRpsField
            End Get
            Set(ByVal value As tcRps())
                Me.listaRpsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(ByVal value As String)
                Me.idField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")> _
    Partial Public Class tcRps

        Private infRpsField As tcInfRps

        Private signatureField As SignatureType

        '''<remarks/>
        Public Property InfRps() As tcInfRps
            Get
                Return Me.infRpsField
            End Get
            Set(ByVal value As tcInfRps)
                Me.infRpsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")> _
        Public Property Signature() As SignatureType
            Get
                Return Me.signatureField
            End Get
            Set(ByVal value As SignatureType)
                Me.signatureField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")> _
    Partial Public Class tcInfRps

        Private identificacaoRpsField As tcIdentificacaoRps

        Private dataEmissaoField As Date

        Private naturezaOperacaoField As SByte

        Private regimeEspecialTributacaoField As SByte

        Private regimeEspecialTributacaoFieldSpecified As Boolean

        Private optanteSimplesNacionalField As SByte

        Private incentivadorCulturalField As SByte

        Private statusField As SByte

        Private rpsSubstituidoField As tcIdentificacaoRps

        Private servicoField As tcDadosServico

        Private prestadorField As tcIdentificacaoPrestador

        Private tomadorField As tcDadosTomador

        Private intermediarioServicoField As tcIdentificacaoIntermediarioServico

        Private construcaoCivilField As tcDadosConstrucaoCivil

        Private idField As String

        '''<remarks/>
        Public Property IdentificacaoRps() As tcIdentificacaoRps
            Get
                Return Me.identificacaoRpsField
            End Get
            Set(ByVal value As tcIdentificacaoRps)
                Me.identificacaoRpsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DataEmissao() As Date
            Get
                Return Me.dataEmissaoField
            End Get
            Set(ByVal value As Date)
                Me.dataEmissaoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NaturezaOperacao() As SByte
            Get
                Return Me.naturezaOperacaoField
            End Get
            Set(ByVal value As SByte)
                Me.naturezaOperacaoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RegimeEspecialTributacao() As SByte
            Get
                Return Me.regimeEspecialTributacaoField
            End Get
            Set(ByVal value As SByte)
                Me.regimeEspecialTributacaoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property RegimeEspecialTributacaoSpecified() As Boolean
            Get
                Return Me.regimeEspecialTributacaoFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.regimeEspecialTributacaoFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OptanteSimplesNacional() As SByte
            Get
                Return Me.optanteSimplesNacionalField
            End Get
            Set(ByVal value As SByte)
                Me.optanteSimplesNacionalField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property IncentivadorCultural() As SByte
            Get
                Return Me.incentivadorCulturalField
            End Get
            Set(ByVal value As SByte)
                Me.incentivadorCulturalField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Status() As SByte
            Get
                Return Me.statusField
            End Get
            Set(ByVal value As SByte)
                Me.statusField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RpsSubstituido() As tcIdentificacaoRps
            Get
                Return Me.rpsSubstituidoField
            End Get
            Set(ByVal value As tcIdentificacaoRps)
                Me.rpsSubstituidoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Servico() As tcDadosServico
            Get
                Return Me.servicoField
            End Get
            Set(ByVal value As tcDadosServico)
                Me.servicoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Prestador() As tcIdentificacaoPrestador
            Get
                Return Me.prestadorField
            End Get
            Set(ByVal value As tcIdentificacaoPrestador)
                Me.prestadorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Tomador() As tcDadosTomador
            Get
                Return Me.tomadorField
            End Get
            Set(ByVal value As tcDadosTomador)
                Me.tomadorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property IntermediarioServico() As tcIdentificacaoIntermediarioServico
            Get
                Return Me.intermediarioServicoField
            End Get
            Set(ByVal value As tcIdentificacaoIntermediarioServico)
                Me.intermediarioServicoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ConstrucaoCivil() As tcDadosConstrucaoCivil
            Get
                Return Me.construcaoCivilField
            End Get
            Set(ByVal value As tcDadosConstrucaoCivil)
                Me.construcaoCivilField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(ByVal value As String)
                Me.idField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")> _
    Partial Public Class tcIdentificacaoRps

        Private numeroField As String

        Private serieField As String

        Private tipoField As SByte

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="nonNegativeInteger")> _
        Public Property Numero() As String
            Get
                Return Me.numeroField
            End Get
            Set(ByVal value As String)
                Me.numeroField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Serie() As String
            Get
                Return Me.serieField
            End Get
            Set(ByVal value As String)
                Me.serieField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Tipo() As SByte
            Get
                Return Me.tipoField
            End Get
            Set(ByVal value As SByte)
                Me.tipoField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")> _
    Partial Public Class tcDadosServico

        Private valoresField As tcValores

        Private itemListaServicoField As String

        Private codigoCnaeField As Integer

        Private codigoCnaeFieldSpecified As Boolean

        Private codigoTributacaoMunicipioField As String

        Private discriminacaoField As String

        Private codigoMunicipioField As Integer

        '''<remarks/>
        Public Property Valores() As tcValores
            Get
                Return Me.valoresField
            End Get
            Set(ByVal value As tcValores)
                Me.valoresField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ItemListaServico() As String
            Get
                Return Me.itemListaServicoField
            End Get
            Set(ByVal value As String)
                Me.itemListaServicoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CodigoCnae() As Integer
            Get
                Return Me.codigoCnaeField
            End Get
            Set(ByVal value As Integer)
                Me.codigoCnaeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property CodigoCnaeSpecified() As Boolean
            Get
                Return Me.codigoCnaeFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.codigoCnaeFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CodigoTributacaoMunicipio() As String
            Get
                Return Me.codigoTributacaoMunicipioField
            End Get
            Set(ByVal value As String)
                Me.codigoTributacaoMunicipioField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Discriminacao() As String
            Get
                Return Me.discriminacaoField
            End Get
            Set(ByVal value As String)
                Me.discriminacaoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CodigoMunicipio() As Integer
            Get
                Return Me.codigoMunicipioField
            End Get
            Set(ByVal value As Integer)
                Me.codigoMunicipioField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")> _
    Partial Public Class tcValores

        Private valorServicosField As Decimal

        Private valorDeducoesField As Decimal

        Private valorDeducoesFieldSpecified As Boolean

        Private valorPisField As Decimal

        Private valorPisFieldSpecified As Boolean

        Private valorCofinsField As Decimal

        Private valorCofinsFieldSpecified As Boolean

        Private valorInssField As Decimal

        Private valorInssFieldSpecified As Boolean

        Private valorIrField As Decimal

        Private valorIrFieldSpecified As Boolean

        Private valorCsllField As Decimal

        Private valorCsllFieldSpecified As Boolean

        Private issRetidoField As SByte

        Private valorIssField As Decimal

        Private valorIssFieldSpecified As Boolean

        Private valorIssRetidoField As Decimal

        Private valorIssRetidoFieldSpecified As Boolean

        Private outrasRetencoesField As Decimal

        Private outrasRetencoesFieldSpecified As Boolean

        Private baseCalculoField As Decimal

        Private baseCalculoFieldSpecified As Boolean

        Private aliquotaField As Decimal

        Private aliquotaFieldSpecified As Boolean

        Private valorLiquidoNfseField As Decimal

        Private valorLiquidoNfseFieldSpecified As Boolean

        Private descontoIncondicionadoField As Decimal

        Private descontoIncondicionadoFieldSpecified As Boolean

        Private descontoCondicionadoField As Decimal

        Private descontoCondicionadoFieldSpecified As Boolean

        '''<remarks/>
        Public Property ValorServicos() As Decimal
            Get
                Return Me.valorServicosField
            End Get
            Set(ByVal value As Decimal)
                Me.valorServicosField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ValorDeducoes() As Decimal
            Get
                Return Me.valorDeducoesField
            End Get
            Set(ByVal value As Decimal)
                Me.valorDeducoesField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ValorDeducoesSpecified() As Boolean
            Get
                Return Me.valorDeducoesFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.valorDeducoesFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ValorPis() As Decimal
            Get
                Return Me.valorPisField
            End Get
            Set(ByVal value As Decimal)
                Me.valorPisField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ValorPisSpecified() As Boolean
            Get
                Return Me.valorPisFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.valorPisFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ValorCofins() As Decimal
            Get
                Return Me.valorCofinsField
            End Get
            Set(ByVal value As Decimal)
                Me.valorCofinsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ValorCofinsSpecified() As Boolean
            Get
                Return Me.valorCofinsFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.valorCofinsFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ValorInss() As Decimal
            Get
                Return Me.valorInssField
            End Get
            Set(ByVal value As Decimal)
                Me.valorInssField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ValorInssSpecified() As Boolean
            Get
                Return Me.valorInssFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.valorInssFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ValorIr() As Decimal
            Get
                Return Me.valorIrField
            End Get
            Set(ByVal value As Decimal)
                Me.valorIrField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ValorIrSpecified() As Boolean
            Get
                Return Me.valorIrFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.valorIrFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ValorCsll() As Decimal
            Get
                Return Me.valorCsllField
            End Get
            Set(ByVal value As Decimal)
                Me.valorCsllField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ValorCsllSpecified() As Boolean
            Get
                Return Me.valorCsllFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.valorCsllFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property IssRetido() As SByte
            Get
                Return Me.issRetidoField
            End Get
            Set(ByVal value As SByte)
                Me.issRetidoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ValorIss() As Decimal
            Get
                Return Me.valorIssField
            End Get
            Set(ByVal value As Decimal)
                Me.valorIssField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ValorIssSpecified() As Boolean
            Get
                Return Me.valorIssFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.valorIssFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ValorIssRetido() As Decimal
            Get
                Return Me.valorIssRetidoField
            End Get
            Set(ByVal value As Decimal)
                Me.valorIssRetidoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ValorIssRetidoSpecified() As Boolean
            Get
                Return Me.valorIssRetidoFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.valorIssRetidoFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property OutrasRetencoes() As Decimal
            Get
                Return Me.outrasRetencoesField
            End Get
            Set(ByVal value As Decimal)
                Me.outrasRetencoesField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property OutrasRetencoesSpecified() As Boolean
            Get
                Return Me.outrasRetencoesFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.outrasRetencoesFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property BaseCalculo() As Decimal
            Get
                Return Me.baseCalculoField
            End Get
            Set(ByVal value As Decimal)
                Me.baseCalculoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property BaseCalculoSpecified() As Boolean
            Get
                Return Me.baseCalculoFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.baseCalculoFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Aliquota() As Decimal
            Get
                Return Me.aliquotaField
            End Get
            Set(ByVal value As Decimal)
                Me.aliquotaField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property AliquotaSpecified() As Boolean
            Get
                Return Me.aliquotaFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.aliquotaFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ValorLiquidoNfse() As Decimal
            Get
                Return Me.valorLiquidoNfseField
            End Get
            Set(ByVal value As Decimal)
                Me.valorLiquidoNfseField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ValorLiquidoNfseSpecified() As Boolean
            Get
                Return Me.valorLiquidoNfseFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.valorLiquidoNfseFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DescontoIncondicionado() As Decimal
            Get
                Return Me.descontoIncondicionadoField
            End Get
            Set(ByVal value As Decimal)
                Me.descontoIncondicionadoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property DescontoIncondicionadoSpecified() As Boolean
            Get
                Return Me.descontoIncondicionadoFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.descontoIncondicionadoFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DescontoCondicionado() As Decimal
            Get
                Return Me.descontoCondicionadoField
            End Get
            Set(ByVal value As Decimal)
                Me.descontoCondicionadoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property DescontoCondicionadoSpecified() As Boolean
            Get
                Return Me.descontoCondicionadoFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.descontoCondicionadoFieldSpecified = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")> _
    Partial Public Class tcIdentificacaoPrestador

        Private cnpjField As String

        Private inscricaoMunicipalField As String

        '''<remarks/>
        Public Property Cnpj() As String
            Get
                Return Me.cnpjField
            End Get
            Set(ByVal value As String)
                Me.cnpjField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property InscricaoMunicipal() As String
            Get
                Return Me.inscricaoMunicipalField
            End Get
            Set(ByVal value As String)
                Me.inscricaoMunicipalField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")> _
    Partial Public Class tcDadosTomador

        Private identificacaoTomadorField As tcIdentificacaoTomador

        Private razaoSocialField As String

        Private enderecoField As tcEndereco

        Private contatoField As tcContato

        '''<remarks/>
        Public Property IdentificacaoTomador() As tcIdentificacaoTomador
            Get
                Return Me.identificacaoTomadorField
            End Get
            Set(ByVal value As tcIdentificacaoTomador)
                Me.identificacaoTomadorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RazaoSocial() As String
            Get
                Return Me.razaoSocialField
            End Get
            Set(ByVal value As String)
                Me.razaoSocialField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Endereco() As tcEndereco
            Get
                Return Me.enderecoField
            End Get
            Set(ByVal value As tcEndereco)
                Me.enderecoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Contato() As tcContato
            Get
                Return Me.contatoField
            End Get
            Set(ByVal value As tcContato)
                Me.contatoField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")> _
    Partial Public Class tcIdentificacaoTomador

        Private cpfCnpjField As tcCpfCnpj

        Private inscricaoMunicipalField As String

        '''<remarks/>
        Public Property CpfCnpj() As tcCpfCnpj
            Get
                Return Me.cpfCnpjField
            End Get
            Set(ByVal value As tcCpfCnpj)
                Me.cpfCnpjField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property InscricaoMunicipal() As String
            Get
                Return Me.inscricaoMunicipalField
            End Get
            Set(ByVal value As String)
                Me.inscricaoMunicipalField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")> _
    Partial Public Class tcCpfCnpj

        Private itemField As String

        Private itemElementNameField As ItemChoiceType

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Cnpj", GetType(String)), _
         System.Xml.Serialization.XmlElementAttribute("Cpf", GetType(String)), _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")> _
        Public Property Item() As String
            Get
                Return Me.itemField
            End Get
            Set(ByVal value As String)
                Me.itemField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ItemElementName() As ItemChoiceType
            Get
                Return Me.itemElementNameField
            End Get
            Set(ByVal value As ItemChoiceType)
                Me.itemElementNameField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd", IncludeInSchema:=False)> _
    Public Enum ItemChoiceType

        '''<remarks/>
        Cnpj

        '''<remarks/>
        Cpf
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")> _
    Partial Public Class tcEndereco

        Private enderecoField As String

        Private numeroField As String

        Private complementoField As String

        Private bairroField As String

        Private codigoMunicipioField As Integer

        Private codigoMunicipioFieldSpecified As Boolean

        Private ufField As String

        Private cepField As Integer

        Private cepFieldSpecified As Boolean

        '''<remarks/>
        Public Property Endereco() As String
            Get
                Return Me.enderecoField
            End Get
            Set(ByVal value As String)
                Me.enderecoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Numero() As String
            Get
                Return Me.numeroField
            End Get
            Set(ByVal value As String)
                Me.numeroField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Complemento() As String
            Get
                Return Me.complementoField
            End Get
            Set(ByVal value As String)
                Me.complementoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Bairro() As String
            Get
                Return Me.bairroField
            End Get
            Set(ByVal value As String)
                Me.bairroField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CodigoMunicipio() As Integer
            Get
                Return Me.codigoMunicipioField
            End Get
            Set(ByVal value As Integer)
                Me.codigoMunicipioField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property CodigoMunicipioSpecified() As Boolean
            Get
                Return Me.codigoMunicipioFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.codigoMunicipioFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Uf() As String
            Get
                Return Me.ufField
            End Get
            Set(ByVal value As String)
                Me.ufField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Cep() As Integer
            Get
                Return Me.cepField
            End Get
            Set(ByVal value As Integer)
                Me.cepField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property CepSpecified() As Boolean
            Get
                Return Me.cepFieldSpecified
            End Get
            Set(ByVal value As Boolean)
                Me.cepFieldSpecified = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")> _
    Partial Public Class tcContato

        Private telefoneField As String

        Private emailField As String

        '''<remarks/>
        Public Property Telefone() As String
            Get
                Return Me.telefoneField
            End Get
            Set(ByVal value As String)
                Me.telefoneField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set(ByVal value As String)
                Me.emailField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")> _
    Partial Public Class tcIdentificacaoIntermediarioServico

        Private razaoSocialField As String

        Private cpfCnpjField As tcCpfCnpj

        Private inscricaoMunicipalField As String

        '''<remarks/>
        Public Property RazaoSocial() As String
            Get
                Return Me.razaoSocialField
            End Get
            Set(ByVal value As String)
                Me.razaoSocialField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CpfCnpj() As tcCpfCnpj
            Get
                Return Me.cpfCnpjField
            End Get
            Set(ByVal value As tcCpfCnpj)
                Me.cpfCnpjField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property InscricaoMunicipal() As String
            Get
                Return Me.inscricaoMunicipalField
            End Get
            Set(ByVal value As String)
                Me.inscricaoMunicipalField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ginfes.com.br/tipos_v03.xsd")> _
    Partial Public Class tcDadosConstrucaoCivil

        Private codigoObraField As String

        Private artField As String

        '''<remarks/>
        Public Property CodigoObra() As String
            Get
                Return Me.codigoObraField
            End Get
            Set(ByVal value As String)
                Me.codigoObraField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Art() As String
            Get
                Return Me.artField
            End Get
            Set(ByVal value As String)
                Me.artField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("Signature", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class SignatureType

        Private signedInfoField As SignedInfoType

        Private signatureValueField As SignatureValueType

        Private keyInfoField As KeyInfoType

        Private objectField() As ObjectType

        Private idField As String

        '''<remarks/>
        Public Property SignedInfo() As SignedInfoType
            Get
                Return Me.signedInfoField
            End Get
            Set(ByVal value As SignedInfoType)
                Me.signedInfoField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SignatureValue() As SignatureValueType
            Get
                Return Me.signatureValueField
            End Get
            Set(ByVal value As SignatureValueType)
                Me.signatureValueField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property KeyInfo() As KeyInfoType
            Get
                Return Me.keyInfoField
            End Get
            Set(ByVal value As KeyInfoType)
                Me.keyInfoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Object")> _
        Public Property [Object]() As ObjectType()
            Get
                Return Me.objectField
            End Get
            Set(ByVal value As ObjectType())
                Me.objectField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(ByVal value As String)
                Me.idField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("SignedInfo", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class SignedInfoType

        Private canonicalizationMethodField As CanonicalizationMethodType

        Private signatureMethodField As SignatureMethodType

        Private referenceField() As ReferenceType

        Private idField As String

        '''<remarks/>
        Public Property CanonicalizationMethod() As CanonicalizationMethodType
            Get
                Return Me.canonicalizationMethodField
            End Get
            Set(ByVal value As CanonicalizationMethodType)
                Me.canonicalizationMethodField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SignatureMethod() As SignatureMethodType
            Get
                Return Me.signatureMethodField
            End Get
            Set(ByVal value As SignatureMethodType)
                Me.signatureMethodField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Reference")> _
        Public Property Reference() As ReferenceType()
            Get
                Return Me.referenceField
            End Get
            Set(ByVal value As ReferenceType())
                Me.referenceField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(ByVal value As String)
                Me.idField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("CanonicalizationMethod", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class CanonicalizationMethodType

        Private anyField() As System.Xml.XmlNode

        Private algorithmField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(), _
         System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set(ByVal value As System.Xml.XmlNode())
                Me.anyField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set(ByVal value As String)
                Me.algorithmField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("SignatureMethod", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class SignatureMethodType

        Private hMACOutputLengthField As String

        Private anyField() As System.Xml.XmlNode

        Private algorithmField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")> _
        Public Property HMACOutputLength() As String
            Get
                Return Me.hMACOutputLengthField
            End Get
            Set(ByVal value As String)
                Me.hMACOutputLengthField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(), _
         System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set(ByVal value As System.Xml.XmlNode())
                Me.anyField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set(ByVal value As String)
                Me.algorithmField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("Reference", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class ReferenceType

        Private transformsField() As TransformType

        Private digestMethodField As DigestMethodType

        Private digestValueField() As Byte

        Private idField As String

        Private uRIField As String

        Private typeField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable:=False)> _
        Public Property Transforms() As TransformType()
            Get
                Return Me.transformsField
            End Get
            Set(ByVal value As TransformType())
                Me.transformsField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DigestMethod() As DigestMethodType
            Get
                Return Me.digestMethodField
            End Get
            Set(ByVal value As DigestMethodType)
                Me.digestMethodField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property DigestValue() As Byte()
            Get
                Return Me.digestValueField
            End Get
            Set(ByVal value As Byte())
                Me.digestValueField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(ByVal value As String)
                Me.idField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property URI() As String
            Get
                Return Me.uRIField
            End Get
            Set(ByVal value As String)
                Me.uRIField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set(ByVal value As String)
                Me.typeField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("Transform", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class TransformType

        Private itemsField() As Object

        Private textField() As String

        Private algorithmField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(), _
         System.Xml.Serialization.XmlElementAttribute("XPath", GetType(String))> _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set(ByVal value As Object())
                Me.itemsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.TextField
            End Get
            Set(ByVal value As String())
                Me.TextField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set(ByVal value As String)
                Me.algorithmField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("DigestMethod", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class DigestMethodType

        Private anyField() As System.Xml.XmlNode

        Private algorithmField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(), _
         System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set(ByVal value As System.Xml.XmlNode())
                Me.anyField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set(ByVal value As String)
                Me.algorithmField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("SignatureValue", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class SignatureValueType

        Private idField As String

        Private valueField() As Byte

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(ByVal value As String)
                Me.idField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="base64Binary")> _
        Public Property Value() As Byte()
            Get
                Return Me.valueField
            End Get
            Set(ByVal value As Byte())
                Me.valueField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("KeyInfo", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class KeyInfoType

        Private itemsField() As Object

        Private itemsElementNameField() As ItemsChoiceType2

        Private textField() As String

        Private idField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(), _
         System.Xml.Serialization.XmlElementAttribute("KeyName", GetType(String)), _
         System.Xml.Serialization.XmlElementAttribute("KeyValue", GetType(KeyValueType)), _
         System.Xml.Serialization.XmlElementAttribute("MgmtData", GetType(String)), _
         System.Xml.Serialization.XmlElementAttribute("PGPData", GetType(PGPDataType)), _
         System.Xml.Serialization.XmlElementAttribute("RetrievalMethod", GetType(RetrievalMethodType)), _
         System.Xml.Serialization.XmlElementAttribute("SPKIData", GetType(SPKIDataType)), _
         System.Xml.Serialization.XmlElementAttribute("X509Data", GetType(X509DataType)), _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")> _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set(ByVal value As Object())
                Me.itemsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"), _
         System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ItemsElementName() As ItemsChoiceType2()
            Get
                Return Me.itemsElementNameField
            End Get
            Set(ByVal value As ItemsChoiceType2())
                Me.itemsElementNameField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.TextField
            End Get
            Set(ByVal value As String())
                Me.TextField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(ByVal value As String)
                Me.idField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("KeyValue", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class KeyValueType

        Private itemField As Object

        Private textField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(), _
         System.Xml.Serialization.XmlElementAttribute("DSAKeyValue", GetType(DSAKeyValueType)), _
         System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", GetType(RSAKeyValueType))> _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set(ByVal value As Object)
                Me.itemField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.TextField
            End Get
            Set(ByVal value As String())
                Me.TextField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("DSAKeyValue", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class DSAKeyValueType

        Private pField() As Byte

        Private qField() As Byte

        Private gField() As Byte

        Private yField() As Byte

        Private jField() As Byte

        Private seedField() As Byte

        Private pgenCounterField() As Byte

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property P() As Byte()
            Get
                Return Me.pField
            End Get
            Set(ByVal value As Byte())
                Me.pField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property Q() As Byte()
            Get
                Return Me.qField
            End Get
            Set(ByVal value As Byte())
                Me.qField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property G() As Byte()
            Get
                Return Me.gField
            End Get
            Set(ByVal value As Byte())
                Me.gField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property Y() As Byte()
            Get
                Return Me.yField
            End Get
            Set(ByVal value As Byte())
                Me.yField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property J() As Byte()
            Get
                Return Me.jField
            End Get
            Set(ByVal value As Byte())
                Me.jField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property Seed() As Byte()
            Get
                Return Me.seedField
            End Get
            Set(ByVal value As Byte())
                Me.seedField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property PgenCounter() As Byte()
            Get
                Return Me.pgenCounterField
            End Get
            Set(ByVal value As Byte())
                Me.pgenCounterField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("RSAKeyValue", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class RSAKeyValueType

        Private modulusField() As Byte

        Private exponentField() As Byte

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property Modulus() As Byte()
            Get
                Return Me.modulusField
            End Get
            Set(ByVal value As Byte())
                Me.modulusField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> _
        Public Property Exponent() As Byte()
            Get
                Return Me.exponentField
            End Get
            Set(ByVal value As Byte())
                Me.exponentField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("PGPData", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class PGPDataType

        Private itemsField() As Object

        Private itemsElementNameField() As ItemsChoiceType1

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(), _
         System.Xml.Serialization.XmlElementAttribute("PGPKeyID", GetType(Byte()), DataType:="base64Binary"), _
         System.Xml.Serialization.XmlElementAttribute("PGPKeyPacket", GetType(Byte()), DataType:="base64Binary"), _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")> _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set(ByVal value As Object())
                Me.itemsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"), _
         System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ItemsElementName() As ItemsChoiceType1()
            Get
                Return Me.itemsElementNameField
            End Get
            Set(ByVal value As ItemsChoiceType1())
                Me.itemsElementNameField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema:=False)> _
    Public Enum ItemsChoiceType1

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("##any:")> _
        Item

        '''<remarks/>
        PGPKeyID

        '''<remarks/>
        PGPKeyPacket
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("RetrievalMethod", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class RetrievalMethodType

        Private transformsField() As TransformType

        Private uRIField As String

        Private typeField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable:=False)> _
        Public Property Transforms() As TransformType()
            Get
                Return Me.transformsField
            End Get
            Set(ByVal value As TransformType())
                Me.transformsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property URI() As String
            Get
                Return Me.uRIField
            End Get
            Set(ByVal value As String)
                Me.uRIField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set(ByVal value As String)
                Me.typeField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("SPKIData", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class SPKIDataType

        Private sPKISexpField()() As Byte

        Private anyField As System.Xml.XmlElement

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("SPKISexp", DataType:="base64Binary")> _
        Public Property SPKISexp() As Byte()()
            Get
                Return Me.sPKISexpField
            End Get
            Set(ByVal value As Byte()())
                Me.sPKISexpField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlElement
            Get
                Return Me.anyField
            End Get
            Set(ByVal value As System.Xml.XmlElement)
                Me.anyField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("X509Data", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class X509DataType

        Private itemsField() As Object

        Private itemsElementNameField() As ItemsChoiceType

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(), _
         System.Xml.Serialization.XmlElementAttribute("X509CRL", GetType(Byte()), DataType:="base64Binary"), _
         System.Xml.Serialization.XmlElementAttribute("X509Certificate", GetType(Byte()), DataType:="base64Binary"), _
         System.Xml.Serialization.XmlElementAttribute("X509IssuerSerial", GetType(X509IssuerSerialType)), _
         System.Xml.Serialization.XmlElementAttribute("X509SKI", GetType(Byte()), DataType:="base64Binary"), _
         System.Xml.Serialization.XmlElementAttribute("X509SubjectName", GetType(String)), _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")> _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set(ByVal value As Object())
                Me.itemsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"), _
         System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property ItemsElementName() As ItemsChoiceType()
            Get
                Return Me.itemsElementNameField
            End Get
            Set(ByVal value As ItemsChoiceType())
                Me.itemsElementNameField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")> _
    Partial Public Class X509IssuerSerialType

        Private x509IssuerNameField As String

        Private x509SerialNumberField As String

        '''<remarks/>
        Public Property X509IssuerName() As String
            Get
                Return Me.x509IssuerNameField
            End Get
            Set(ByVal value As String)
                Me.x509IssuerNameField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")> _
        Public Property X509SerialNumber() As String
            Get
                Return Me.x509SerialNumberField
            End Get
            Set(ByVal value As String)
                Me.x509SerialNumberField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema:=False)> _
    Public Enum ItemsChoiceType

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("##any:")> _
        Item

        '''<remarks/>
        X509CRL

        '''<remarks/>
        X509Certificate

        '''<remarks/>
        X509IssuerSerial

        '''<remarks/>
        X509SKI

        '''<remarks/>
        X509SubjectName
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema:=False)> _
    Public Enum ItemsChoiceType2

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("##any:")> _
        Item

        '''<remarks/>
        KeyName

        '''<remarks/>
        KeyValue

        '''<remarks/>
        MgmtData

        '''<remarks/>
        PGPData

        '''<remarks/>
        RetrievalMethod

        '''<remarks/>
        SPKIData

        '''<remarks/>
        X509Data
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("Object", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class ObjectType

        Private anyField() As System.Xml.XmlNode

        Private idField As String

        Private mimeTypeField As String

        Private encodingField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(), _
         System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set(ByVal value As System.Xml.XmlNode())
                Me.anyField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(ByVal value As String)
                Me.idField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property MimeType() As String
            Get
                Return Me.mimeTypeField
            End Get
            Set(ByVal value As String)
                Me.mimeTypeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property Encoding() As String
            Get
                Return Me.encodingField
            End Get
            Set(ByVal value As String)
                Me.encodingField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("Transforms", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class TransformsType

        Private transformField() As TransformType

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Transform")> _
        Public Property Transform() As TransformType()
            Get
                Return Me.transformField
            End Get
            Set(ByVal value As TransformType())
                Me.transformField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("Manifest", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class ManifestType

        Private referenceField() As ReferenceType

        Private idField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Reference")> _
        Public Property Reference() As ReferenceType()
            Get
                Return Me.referenceField
            End Get
            Set(ByVal value As ReferenceType())
                Me.referenceField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(ByVal value As String)
                Me.idField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("SignatureProperties", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class SignaturePropertiesType

        Private signaturePropertyField() As SignaturePropertyType

        Private idField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("SignatureProperty")> _
        Public Property SignatureProperty() As SignaturePropertyType()
            Get
                Return Me.signaturePropertyField
            End Get
            Set(ByVal value As SignaturePropertyType())
                Me.signaturePropertyField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(ByVal value As String)
                Me.idField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#"), _
     System.Xml.Serialization.XmlRootAttribute("SignatureProperty", [Namespace]:="http://www.w3.org/2000/09/xmldsig#", IsNullable:=False)> _
    Partial Public Class SignaturePropertyType

        Private itemsField() As System.Xml.XmlElement

        Private textField() As String

        Private targetField As String

        Private idField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Items() As System.Xml.XmlElement()
            Get
                Return Me.itemsField
            End Get
            Set(ByVal value As System.Xml.XmlElement())
                Me.itemsField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Text() As String()
            Get
                Return Me.TextField
            End Get
            Set(ByVal value As String())
                Me.TextField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")> _
        Public Property Target() As String
            Get
                Return Me.targetField
            End Get
            Set(ByVal value As String)
                Me.targetField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")> _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set(ByVal value As String)
                Me.idField = value
            End Set
        End Property
    End Class
End Namespace
