'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace br.com.issnetonline.producao
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServicosSoap", [Namespace]:="http://www.issnetonline.com.br/webservice/nfd")>  _
    Partial Public Class Servicos
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private RecepcionarLoteRpsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaSituacaoLoteRPSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarSituacaoLoteRPSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultaNFSePorRPSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarNFSePorRPSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarLoteRpsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarNfseOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarUrlVisualizacaoNfseOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ConsultarUrlVisualizacaoNfseSerieOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CancelarNfseOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.INTERACTI.My.MySettings.Default.INTERACTI_br_com_issnetonline_producao_Servicos
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event RecepcionarLoteRpsCompleted As RecepcionarLoteRpsCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaSituacaoLoteRPSCompleted As ConsultaSituacaoLoteRPSCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarSituacaoLoteRPSCompleted As ConsultarSituacaoLoteRPSCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultaNFSePorRPSCompleted As ConsultaNFSePorRPSCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarNFSePorRPSCompleted As ConsultarNFSePorRPSCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarLoteRpsCompleted As ConsultarLoteRpsCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarNfseCompleted As ConsultarNfseCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarUrlVisualizacaoNfseCompleted As ConsultarUrlVisualizacaoNfseCompletedEventHandler
        
        '''<remarks/>
        Public Event ConsultarUrlVisualizacaoNfseSerieCompleted As ConsultarUrlVisualizacaoNfseSerieCompletedEventHandler
        
        '''<remarks/>
        Public Event CancelarNfseCompleted As CancelarNfseCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.issnetonline.com.br/webservice/nfd/RecepcionarLoteRps", RequestNamespace:="http://www.issnetonline.com.br/webservice/nfd", ResponseNamespace:="http://www.issnetonline.com.br/webservice/nfd", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RecepcionarLoteRps(ByVal xml As String) As String
            Dim results() As Object = Me.Invoke("RecepcionarLoteRps", New Object() {xml})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub RecepcionarLoteRpsAsync(ByVal xml As String)
            Me.RecepcionarLoteRpsAsync(xml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RecepcionarLoteRpsAsync(ByVal xml As String, ByVal userState As Object)
            If (Me.RecepcionarLoteRpsOperationCompleted Is Nothing) Then
                Me.RecepcionarLoteRpsOperationCompleted = AddressOf Me.OnRecepcionarLoteRpsOperationCompleted
            End If
            Me.InvokeAsync("RecepcionarLoteRps", New Object() {xml}, Me.RecepcionarLoteRpsOperationCompleted, userState)
        End Sub
        
        Private Sub OnRecepcionarLoteRpsOperationCompleted(ByVal arg As Object)
            If (Not (Me.RecepcionarLoteRpsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RecepcionarLoteRpsCompleted(Me, New RecepcionarLoteRpsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.issnetonline.com.br/webservice/nfd/ConsultaSituacaoLoteRPS", RequestNamespace:="http://www.issnetonline.com.br/webservice/nfd", ResponseNamespace:="http://www.issnetonline.com.br/webservice/nfd", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaSituacaoLoteRPS(ByVal xml As String) As String
            Dim results() As Object = Me.Invoke("ConsultaSituacaoLoteRPS", New Object() {xml})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaSituacaoLoteRPSAsync(ByVal xml As String)
            Me.ConsultaSituacaoLoteRPSAsync(xml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaSituacaoLoteRPSAsync(ByVal xml As String, ByVal userState As Object)
            If (Me.ConsultaSituacaoLoteRPSOperationCompleted Is Nothing) Then
                Me.ConsultaSituacaoLoteRPSOperationCompleted = AddressOf Me.OnConsultaSituacaoLoteRPSOperationCompleted
            End If
            Me.InvokeAsync("ConsultaSituacaoLoteRPS", New Object() {xml}, Me.ConsultaSituacaoLoteRPSOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaSituacaoLoteRPSOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaSituacaoLoteRPSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaSituacaoLoteRPSCompleted(Me, New ConsultaSituacaoLoteRPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.issnetonline.com.br/webservice/nfd/ConsultarSituacaoLoteRPS", RequestNamespace:="http://www.issnetonline.com.br/webservice/nfd", ResponseNamespace:="http://www.issnetonline.com.br/webservice/nfd", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarSituacaoLoteRPS(ByVal xml As String) As String
            Dim results() As Object = Me.Invoke("ConsultarSituacaoLoteRPS", New Object() {xml})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarSituacaoLoteRPSAsync(ByVal xml As String)
            Me.ConsultarSituacaoLoteRPSAsync(xml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarSituacaoLoteRPSAsync(ByVal xml As String, ByVal userState As Object)
            If (Me.ConsultarSituacaoLoteRPSOperationCompleted Is Nothing) Then
                Me.ConsultarSituacaoLoteRPSOperationCompleted = AddressOf Me.OnConsultarSituacaoLoteRPSOperationCompleted
            End If
            Me.InvokeAsync("ConsultarSituacaoLoteRPS", New Object() {xml}, Me.ConsultarSituacaoLoteRPSOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarSituacaoLoteRPSOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarSituacaoLoteRPSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarSituacaoLoteRPSCompleted(Me, New ConsultarSituacaoLoteRPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.issnetonline.com.br/webservice/nfd/ConsultaNFSePorRPS", RequestNamespace:="http://www.issnetonline.com.br/webservice/nfd", ResponseNamespace:="http://www.issnetonline.com.br/webservice/nfd", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaNFSePorRPS(ByVal xml As String) As String
            Dim results() As Object = Me.Invoke("ConsultaNFSePorRPS", New Object() {xml})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaNFSePorRPSAsync(ByVal xml As String)
            Me.ConsultaNFSePorRPSAsync(xml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaNFSePorRPSAsync(ByVal xml As String, ByVal userState As Object)
            If (Me.ConsultaNFSePorRPSOperationCompleted Is Nothing) Then
                Me.ConsultaNFSePorRPSOperationCompleted = AddressOf Me.OnConsultaNFSePorRPSOperationCompleted
            End If
            Me.InvokeAsync("ConsultaNFSePorRPS", New Object() {xml}, Me.ConsultaNFSePorRPSOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaNFSePorRPSOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaNFSePorRPSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaNFSePorRPSCompleted(Me, New ConsultaNFSePorRPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.issnetonline.com.br/webservice/nfd/ConsultarNFSePorRPS", RequestNamespace:="http://www.issnetonline.com.br/webservice/nfd", ResponseNamespace:="http://www.issnetonline.com.br/webservice/nfd", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarNFSePorRPS(ByVal xml As String) As String
            Dim results() As Object = Me.Invoke("ConsultarNFSePorRPS", New Object() {xml})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarNFSePorRPSAsync(ByVal xml As String)
            Me.ConsultarNFSePorRPSAsync(xml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarNFSePorRPSAsync(ByVal xml As String, ByVal userState As Object)
            If (Me.ConsultarNFSePorRPSOperationCompleted Is Nothing) Then
                Me.ConsultarNFSePorRPSOperationCompleted = AddressOf Me.OnConsultarNFSePorRPSOperationCompleted
            End If
            Me.InvokeAsync("ConsultarNFSePorRPS", New Object() {xml}, Me.ConsultarNFSePorRPSOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarNFSePorRPSOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarNFSePorRPSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarNFSePorRPSCompleted(Me, New ConsultarNFSePorRPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.issnetonline.com.br/webservice/nfd/ConsultarLoteRps", RequestNamespace:="http://www.issnetonline.com.br/webservice/nfd", ResponseNamespace:="http://www.issnetonline.com.br/webservice/nfd", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarLoteRps(ByVal xml As String) As String
            Dim results() As Object = Me.Invoke("ConsultarLoteRps", New Object() {xml})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarLoteRpsAsync(ByVal xml As String)
            Me.ConsultarLoteRpsAsync(xml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarLoteRpsAsync(ByVal xml As String, ByVal userState As Object)
            If (Me.ConsultarLoteRpsOperationCompleted Is Nothing) Then
                Me.ConsultarLoteRpsOperationCompleted = AddressOf Me.OnConsultarLoteRpsOperationCompleted
            End If
            Me.InvokeAsync("ConsultarLoteRps", New Object() {xml}, Me.ConsultarLoteRpsOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarLoteRpsOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarLoteRpsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarLoteRpsCompleted(Me, New ConsultarLoteRpsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.issnetonline.com.br/webservice/nfd/ConsultarNfse", RequestNamespace:="http://www.issnetonline.com.br/webservice/nfd", ResponseNamespace:="http://www.issnetonline.com.br/webservice/nfd", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarNfse(ByVal xml As String) As String
            Dim results() As Object = Me.Invoke("ConsultarNfse", New Object() {xml})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarNfseAsync(ByVal xml As String)
            Me.ConsultarNfseAsync(xml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarNfseAsync(ByVal xml As String, ByVal userState As Object)
            If (Me.ConsultarNfseOperationCompleted Is Nothing) Then
                Me.ConsultarNfseOperationCompleted = AddressOf Me.OnConsultarNfseOperationCompleted
            End If
            Me.InvokeAsync("ConsultarNfse", New Object() {xml}, Me.ConsultarNfseOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarNfseOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarNfseCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarNfseCompleted(Me, New ConsultarNfseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.issnetonline.com.br/webservice/nfd/ConsultarUrlVisualizacaoNfse", RequestNamespace:="http://www.issnetonline.com.br/webservice/nfd", ResponseNamespace:="http://www.issnetonline.com.br/webservice/nfd", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarUrlVisualizacaoNfse(ByVal xml As String) As String
            Dim results() As Object = Me.Invoke("ConsultarUrlVisualizacaoNfse", New Object() {xml})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarUrlVisualizacaoNfseAsync(ByVal xml As String)
            Me.ConsultarUrlVisualizacaoNfseAsync(xml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarUrlVisualizacaoNfseAsync(ByVal xml As String, ByVal userState As Object)
            If (Me.ConsultarUrlVisualizacaoNfseOperationCompleted Is Nothing) Then
                Me.ConsultarUrlVisualizacaoNfseOperationCompleted = AddressOf Me.OnConsultarUrlVisualizacaoNfseOperationCompleted
            End If
            Me.InvokeAsync("ConsultarUrlVisualizacaoNfse", New Object() {xml}, Me.ConsultarUrlVisualizacaoNfseOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarUrlVisualizacaoNfseOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarUrlVisualizacaoNfseCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarUrlVisualizacaoNfseCompleted(Me, New ConsultarUrlVisualizacaoNfseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.issnetonline.com.br/webservice/nfd/ConsultarUrlVisualizacaoNfseSerie", RequestNamespace:="http://www.issnetonline.com.br/webservice/nfd", ResponseNamespace:="http://www.issnetonline.com.br/webservice/nfd", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarUrlVisualizacaoNfseSerie(ByVal xml As String) As String
            Dim results() As Object = Me.Invoke("ConsultarUrlVisualizacaoNfseSerie", New Object() {xml})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarUrlVisualizacaoNfseSerieAsync(ByVal xml As String)
            Me.ConsultarUrlVisualizacaoNfseSerieAsync(xml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarUrlVisualizacaoNfseSerieAsync(ByVal xml As String, ByVal userState As Object)
            If (Me.ConsultarUrlVisualizacaoNfseSerieOperationCompleted Is Nothing) Then
                Me.ConsultarUrlVisualizacaoNfseSerieOperationCompleted = AddressOf Me.OnConsultarUrlVisualizacaoNfseSerieOperationCompleted
            End If
            Me.InvokeAsync("ConsultarUrlVisualizacaoNfseSerie", New Object() {xml}, Me.ConsultarUrlVisualizacaoNfseSerieOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarUrlVisualizacaoNfseSerieOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarUrlVisualizacaoNfseSerieCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarUrlVisualizacaoNfseSerieCompleted(Me, New ConsultarUrlVisualizacaoNfseSerieCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.issnetonline.com.br/webservice/nfd/CancelarNfse", RequestNamespace:="http://www.issnetonline.com.br/webservice/nfd", ResponseNamespace:="http://www.issnetonline.com.br/webservice/nfd", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CancelarNfse(ByVal xml As String) As String
            Dim results() As Object = Me.Invoke("CancelarNfse", New Object() {xml})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CancelarNfseAsync(ByVal xml As String)
            Me.CancelarNfseAsync(xml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CancelarNfseAsync(ByVal xml As String, ByVal userState As Object)
            If (Me.CancelarNfseOperationCompleted Is Nothing) Then
                Me.CancelarNfseOperationCompleted = AddressOf Me.OnCancelarNfseOperationCompleted
            End If
            Me.InvokeAsync("CancelarNfse", New Object() {xml}, Me.CancelarNfseOperationCompleted, userState)
        End Sub
        
        Private Sub OnCancelarNfseOperationCompleted(ByVal arg As Object)
            If (Not (Me.CancelarNfseCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CancelarNfseCompleted(Me, New CancelarNfseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub RecepcionarLoteRpsCompletedEventHandler(ByVal sender As Object, ByVal e As RecepcionarLoteRpsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RecepcionarLoteRpsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ConsultaSituacaoLoteRPSCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaSituacaoLoteRPSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaSituacaoLoteRPSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ConsultarSituacaoLoteRPSCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarSituacaoLoteRPSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarSituacaoLoteRPSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ConsultaNFSePorRPSCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaNFSePorRPSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaNFSePorRPSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ConsultarNFSePorRPSCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarNFSePorRPSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarNFSePorRPSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ConsultarLoteRpsCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarLoteRpsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarLoteRpsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ConsultarNfseCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarNfseCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarNfseCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ConsultarUrlVisualizacaoNfseCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarUrlVisualizacaoNfseCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarUrlVisualizacaoNfseCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ConsultarUrlVisualizacaoNfseSerieCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarUrlVisualizacaoNfseSerieCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarUrlVisualizacaoNfseSerieCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub CancelarNfseCompletedEventHandler(ByVal sender As Object, ByVal e As CancelarNfseCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CancelarNfseCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
